# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title                   : Kommunistisk Parti Aarhus
email                   : cafeoskar@kommunister.dk
description             : >- # this means to ignore newlines until "baseurl:"
  Vi er den aarhusianske partiafdeling af Kommunistisk Parti. Vi kæmper for et socialistisk velfærdssamfund med lige rettigheder til alle og et aktivt deltagerdemokrati.
url                     : "https://kpaarhus.github.io"
baseurl                 : "/"
minimal_mistakes_skin   : "air"
search                  : true
name                    : "Kommunistisk Parti Aarhus"
logo                    : "/assets/icons/android-chrome-192x192.png"
teaser                  : "/assets/images/banner.jpg"
#og_image                : "/assets/images/logo.png"  # Skal være min 120*120 og max 1 MB
date_format             : "%-d/%-m %Y"

# Build settings
markdown                : kramdown
remote_theme            : mmistakes/minimal-mistakes

# Outputting
permalink               : /:year/:title/
paginate                : 5 # amount of posts to show
paginate_path           : /side:num/
timezone                : Europe/Copenhagen
locale                  : "da-DK"
words_per_minute        : 200

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Kommunistisk Parti Aarhus"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://aarhus.kommunister.dk/"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://www.facebook.com/profile.php?id=100069215655528"


footer:
  links:
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://www.facebook.com/profile.php?id=100069215655528"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: false
      share: true
      related: true
      show_date: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false

#category_archive:
#  type: liquid
#  path: /categories/
tag_archive:
  type: liquid
  path: /emner/

# Prose.io
prose:
  rooturl: '_posts'
  #siteurl: 'http://prose.github.io/starter/'
  #relativeLinks: 'http://prose.github.io/starter/links.jsonp'
  media: 'assets/images'
  metadata:
    _posts:
      - name: "title"
        field:
          element: "text"
          label: "Titel"
      - name: "excerpt"
        field:
          element: "textarea"
          label: "Kort uddrag"
          help: "Skriv evt. et kort uddrag/opsummering af artiklen (gerne under 160 tegn)."
      - name: "splash"
        field:
          element: "text"
          label: "Billede"
          help: "Billede i toppen af artiklen. Skal starte med /assets/images/, fx /assets/images/IMG1234.jpg."
